from app.db.base import Base

REQUIRED_TABLES = {
    "users",
    "user_profiles",
    "email_verification_tokens",
    "password_reset_tokens",
    "sessions",
    "roles",
    "permissions",
    "organizations",
    "organization_memberships",
    "membership_roles",
    "audit_events",
    "consent_records",
    "learner_profiles",
    "learner_goals",
    "learner_preferences",
    "enrollments",
    "lesson_progress",
    "learner_notes",
    "bookmarks",
    "learning_sessions",
    "skills",
    "skill_dependencies",
    "learner_skill_states",
    "skill_evidence",
    "misconceptions",
    "learner_misconceptions",
    "recommendations",
    "recommendation_decisions",
    "diagnostic_attempts",
    "assessments",
    "assessment_versions",
    "questions",
    "question_versions",
    "assessment_attempts",
    "question_responses",
    "missions",
    "mission_versions",
    "mission_stages",
    "mission_objectives",
    "mission_sessions",
    "mission_actions",
    "mission_hint_uses",
    "mission_evidence",
    "mission_submissions",
    "mission_results",
    "investigation_replays",
    "projects",
    "project_milestones",
    "project_submissions",
    "rubrics",
    "rubric_criteria",
    "project_reviews",
    "portfolios",
    "portfolio_artifacts",
    "completion_records",
    "mentor_threads",
    "mentor_learner_memories",
    "mentor_messages",
    "mentor_message_feedback",
    "mentor_interventions",
    "retrieval_queries",
    "retrieval_results",
    "safety_events",
    "ai_usage_events",
    "ai_evaluation_cases",
    "ai_evaluation_results",
    "organization_invitations",
    "membership_history",
    "programmes",
    "cohorts",
    "cohort_staff",
    "cohort_enrollments",
    "cohort_curriculum",
    "assignments",
    "learner_assignments",
    "assignment_submissions",
    "assignment_reviews",
    "notifications",
    "shared_profiles",
    "shared_evidence_items",
    "shared_profile_access",
    "evidence_requests",
    "report_exports",
}

TENANT_OWNED = {
    "audit_events",
    "consent_records",
    "learner_profiles",
    "learner_goals",
    "learner_preferences",
    "enrollments",
    "lesson_progress",
    "learner_notes",
    "bookmarks",
    "learning_sessions",
    "learner_skill_states",
    "skill_evidence",
    "learner_misconceptions",
    "recommendations",
    "recommendation_decisions",
    "diagnostic_attempts",
    "assessment_attempts",
    "question_responses",
    "mission_sessions",
    "mission_actions",
    "mission_hint_uses",
    "mission_evidence",
    "mission_submissions",
    "mission_results",
    "investigation_replays",
    "project_submissions",
    "project_reviews",
    "portfolios",
    "portfolio_artifacts",
    "completion_records",
    "mentor_threads",
    "mentor_learner_memories",
    "mentor_messages",
    "mentor_message_feedback",
    "mentor_interventions",
    "retrieval_queries",
    "safety_events",
    "ai_usage_events",
    "organization_invitations",
    "membership_history",
    "programmes",
    "cohorts",
    "cohort_enrollments",
    "cohort_curriculum",
    "assignments",
    "learner_assignments",
    "assignment_submissions",
    "assignment_reviews",
    "notifications",
    "shared_profiles",
    "shared_evidence_items",
    "evidence_requests",
    "report_exports",
}


def test_competition_schema_contains_every_required_domain_table() -> None:
    assert REQUIRED_TABLES <= set(Base.metadata.tables)


def test_every_learner_record_has_explicit_tenant_ownership() -> None:
    missing = {
        table_name
        for table_name in TENANT_OWNED
        if "organization_id" not in Base.metadata.tables[table_name].columns
    }
    assert missing == set()


def test_private_answer_is_not_stored_on_public_question_record() -> None:
    assert "private_answer" not in Base.metadata.tables["questions"].columns
    assert "private_answer" in Base.metadata.tables["question_versions"].columns


def test_immutable_evidence_has_no_update_timestamp() -> None:
    for table_name in {
        "skill_evidence",
        "mission_actions",
        "mission_hint_uses",
        "mission_results",
        "investigation_replays",
        "safety_events",
        "ai_usage_events",
    }:
        assert "updated_at" not in Base.metadata.tables[table_name].columns
