"""competition foundation schema

Revision ID: 20260728_0001
Revises: 
Create Date: 2026-07-28 12:06:13.623565
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '20260728_0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_evaluation_cases',
    sa.Column('stable_key', sa.String(length=140), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('expected_policy', sa.JSON(), nullable=False),
    sa.Column('reviewer_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_evaluation_cases')),
    sa.UniqueConstraint('stable_key', name=op.f('uq_ai_evaluation_cases_stable_key'))
    )
    op.create_table('assessments',
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('publication_id', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments')),
    sa.UniqueConstraint('stable_key', name=op.f('uq_assessments_stable_key'))
    )
    op.create_table('missions',
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('safety_classification', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions')),
    sa.UniqueConstraint('stable_key', name=op.f('uq_missions_stable_key'))
    )
    op.create_table('permissions',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('key', name=op.f('uq_permissions_key'))
    )
    op.create_table('projects',
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('publication_id', sa.String(length=160), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('stable_key', name=op.f('uq_projects_stable_key'))
    )
    op.create_table('roles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('key', name=op.f('uq_roles_key'))
    )
    op.create_table('skills',
    sa.Column('stable_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_types', sa.JSON(), nullable=False),
    sa.Column('minimum_evidence', sa.Integer(), nullable=False),
    sa.Column('recency_days', sa.Integer(), nullable=False),
    sa.Column('readiness_relevance', sa.Float(), nullable=False),
    sa.Column('profile_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_stable_key'), 'skills', ['stable_key'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_evaluation_results',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['ai_evaluation_cases.id'], name=op.f('fk_ai_evaluation_results_case_id_ai_evaluation_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_evaluation_results'))
    )
    op.create_table('assessment_versions',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_versions_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_versions')),
    sa.UniqueConstraint('assessment_id', 'version', name=op.f('uq_assessment_versions_assessment_id'))
    )
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens'))
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_table('misconceptions',
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_misconceptions_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_misconceptions')),
    sa.UniqueConstraint('stable_key', name=op.f('uq_misconceptions_stable_key'))
    )
    op.create_table('mission_versions',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('fictional_organization', sa.String(length=200), nullable=False),
    sa.Column('business_context', sa.Text(), nullable=False),
    sa.Column('briefing', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_manifest', sa.JSON(), nullable=False),
    sa.Column('evaluator_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('fk_mission_versions_mission_id_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_versions')),
    sa.UniqueConstraint('mission_id', 'version', name=op.f('uq_mission_versions_mission_id'))
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_organizations_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('project_milestones',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_milestones_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_milestones')),
    sa.UniqueConstraint('project_id', 'position', name=op.f('uq_project_milestones_project_id'))
    )
    op.create_table('questions',
    sa.Column('stable_key', sa.String(length=140), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('skill_key', sa.String(length=100), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_questions_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('stable_key', name=op.f('uq_questions_stable_key'))
    )
    op.create_index(op.f('ix_questions_skill_key'), 'questions', ['skill_key'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('rubrics',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_rubrics_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubrics')),
    sa.UniqueConstraint('project_id', 'version', name=op.f('uq_rubrics_project_id'))
    )
    op.create_table('skill_dependencies',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('prerequisite_skill_id', sa.Uuid(), nullable=False),
    sa.Column('minimum_mastery', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skills.id'], name=op.f('fk_skill_dependencies_prerequisite_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_dependencies_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'prerequisite_skill_id', name=op.f('pk_skill_dependencies'))
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('ai_usage_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_usage_events_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_usage_events_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_events'))
    )
    op.create_index(op.f('ix_ai_usage_events_organization_id'), 'ai_usage_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_user_id'), 'ai_usage_events', ['user_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_version_id'], ['assessment_versions.id'], name=op.f('fk_assessment_attempts_assessment_version_id_assessment_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assessment_attempts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_attempts'))
    )
    op.create_index('ix_assessment_attempt_owner', 'assessment_attempts', ['organization_id', 'user_id', 'created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_tenant_time', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.create_table('bookmarks',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_bookmarks_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks')),
    sa.UniqueConstraint('organization_id', 'user_id', 'resource_type', 'resource_id', name=op.f('uq_bookmarks_organization_id'))
    )
    op.create_index(op.f('ix_bookmarks_organization_id'), 'bookmarks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('completion_records',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.String(length=80), nullable=False),
    sa.Column('criteria_version', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.String(length=40), nullable=False),
    sa.Column('scope_id', sa.String(length=160), nullable=False),
    sa.Column('skill_summary', sa.JSON(), nullable=False),
    sa.Column('evidence_summary', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_completion_records_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_completion_records_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_completion_records'))
    )
    op.create_index(op.f('ix_completion_records_organization_id'), 'completion_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_completion_records_user_id'), 'completion_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_completion_records_verification_id'), 'completion_records', ['verification_id'], unique=True)
    op.create_table('consent_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_consent_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consent_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_records')),
    sa.UniqueConstraint('user_id', 'purpose', 'policy_version', name=op.f('uq_consent_records_user_id'))
    )
    op.create_table('enrollments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_publication_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_enrollments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('organization_id', 'user_id', 'course_publication_id', name=op.f('uq_enrollments_organization_id'))
    )
    op.create_index(op.f('ix_enrollments_organization_id'), 'enrollments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('learner_goals',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_key', sa.String(length=80), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learner_goals_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_goals')),
    sa.UniqueConstraint('organization_id', 'user_id', 'goal_key', name=op.f('uq_learner_goals_organization_id'))
    )
    op.create_index(op.f('ix_learner_goals_organization_id'), 'learner_goals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learner_goals_user_id'), 'learner_goals', ['user_id'], unique=False)
    op.create_table('learner_misconceptions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('misconception_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], name=op.f('fk_learner_misconceptions_misconception_id_misconceptions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learner_misconceptions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_misconceptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_misconceptions')),
    sa.UniqueConstraint('organization_id', 'user_id', 'misconception_id', name=op.f('uq_learner_misconceptions_organization_id'))
    )
    op.create_table('learner_notes',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_publication_id', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learner_notes_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_notes'))
    )
    op.create_index('ix_notes_owner_lesson', 'learner_notes', ['organization_id', 'user_id', 'lesson_publication_id'], unique=False)
    op.create_table('learner_preferences',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preference_key', sa.String(length=80), nullable=False),
    sa.Column('preference_value', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learner_preferences_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_preferences')),
    sa.UniqueConstraint('organization_id', 'user_id', 'preference_key', name=op.f('uq_learner_preferences_organization_id'))
    )
    op.create_index(op.f('ix_learner_preferences_organization_id'), 'learner_preferences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learner_preferences_user_id'), 'learner_preferences', ['user_id'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('experience_level', sa.String(length=40), nullable=True),
    sa.Column('weekly_minutes', sa.Integer(), nullable=True),
    sa.Column('networking_confidence', sa.Integer(), nullable=True),
    sa.Column('linux_confidence', sa.Integer(), nullable=True),
    sa.Column('investigation_confidence', sa.Integer(), nullable=True),
    sa.Column('accessibility_needs', sa.Text(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learner_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_learner_profiles_user_id'))
    )
    op.create_index(op.f('ix_learner_profiles_organization_id'), 'learner_profiles', ['organization_id'], unique=False)
    op.create_table('learner_skill_states',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('mastery_estimate', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_strength', sa.Float(), nullable=False),
    sa.Column('independence', sa.Float(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learner_skill_states_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_learner_skill_states_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_skill_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_skill_states')),
    sa.UniqueConstraint('organization_id', 'user_id', 'skill_id', name=op.f('uq_learner_skill_states_organization_id'))
    )
    op.create_index(op.f('ix_learner_skill_states_organization_id'), 'learner_skill_states', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learner_skill_states_user_id'), 'learner_skill_states', ['user_id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.String(length=40), nullable=False),
    sa.Column('activity_id', sa.String(length=160), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_learning_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions'))
    )
    op.create_index('ix_learning_session_owner_start', 'learning_sessions', ['organization_id', 'user_id', 'started_at'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_publication_id', sa.String(length=160), nullable=False),
    sa.Column('lesson_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('percent_complete', sa.Integer(), nullable=False),
    sa.Column('last_position', sa.String(length=160), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lesson_progress_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lesson_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_progress')),
    sa.UniqueConstraint('organization_id', 'user_id', 'lesson_publication_id', name=op.f('uq_lesson_progress_organization_id'))
    )
    op.create_index(op.f('ix_lesson_progress_organization_id'), 'lesson_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_table('mentor_threads',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('context_type', sa.String(length=40), nullable=False),
    sa.Column('context_id', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mentor_threads_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mentor_threads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_threads'))
    )
    op.create_index(op.f('ix_mentor_threads_organization_id'), 'mentor_threads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mentor_threads_user_id'), 'mentor_threads', ['user_id'], unique=False)
    op.create_table('mission_stages',
    sa.Column('mission_version_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('stable_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_version_id'], ['mission_versions.id'], name=op.f('fk_mission_stages_mission_version_id_mission_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_stages')),
    sa.UniqueConstraint('mission_version_id', 'position', name=op.f('uq_mission_stages_mission_version_id'))
    )
    op.create_table('organization_memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name=op.f('uq_organization_memberships_organization_id'))
    )
    op.create_index('ix_membership_user_active', 'organization_memberships', ['user_id', 'is_active'], unique=False)
    op.create_table('portfolios',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_portfolios_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('organization_id', 'user_id', name=op.f('uq_portfolios_organization_id'))
    )
    op.create_table('project_submissions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_project_submissions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_submissions_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_submissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_submissions'))
    )
    op.create_index('ix_project_submission_owner', 'project_submissions', ['organization_id', 'user_id', 'created_at'], unique=False)
    op.create_table('question_versions',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('private_answer', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_versions_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_versions')),
    sa.UniqueConstraint('question_id', 'version', name=op.f('uq_question_versions_question_id'))
    )
    op.create_table('recommendations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.String(length=40), nullable=False),
    sa.Column('activity_id', sa.String(length=160), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('intervention_type', sa.String(length=60), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_recommendations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index('ix_recommendation_owner_status', 'recommendations', ['organization_id', 'user_id', 'status'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('pass_standard', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], name=op.f('fk_rubric_criteria_rubric_id_rubrics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubric_criteria'))
    )
    op.create_table('safety_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('redacted_input_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_safety_events_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_safety_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_events'))
    )
    op.create_index(op.f('ix_safety_events_organization_id'), 'safety_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_safety_events_user_id'), 'safety_events', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('active_organization_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_organization_id'], ['organizations.id'], name=op.f('fk_sessions_active_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index('ix_sessions_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('skill_evidence',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('source_version', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('independence', sa.Float(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_skill_evidence_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_evidence_skill_id_skills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_skill_evidence_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_evidence')),
    sa.UniqueConstraint('provenance_hash', name=op.f('uq_skill_evidence_provenance_hash'))
    )
    op.create_index('ix_skill_evidence_owner_time', 'skill_evidence', ['organization_id', 'user_id', 'occurred_at'], unique=False)
    op.create_table('diagnostic_attempts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_version_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_attempt_id'], ['assessment_attempts.id'], name=op.f('fk_diagnostic_attempts_assessment_attempt_id_assessment_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_version_id'], ['assessment_versions.id'], name=op.f('fk_diagnostic_attempts_assessment_version_id_assessment_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_diagnostic_attempts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diagnostic_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_attempts')),
    sa.UniqueConstraint('assessment_attempt_id', name=op.f('uq_diagnostic_attempts_assessment_attempt_id'))
    )
    op.create_index('ix_diagnostic_owner_started', 'diagnostic_attempts', ['organization_id', 'user_id', 'created_at'], unique=False)
    op.create_table('membership_roles',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_membership_roles_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_membership_roles_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'role_id', name=op.f('pk_membership_roles'))
    )
    op.create_table('mentor_interventions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.String(length=60), nullable=False),
    sa.Column('selected_mode', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mentor_interventions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['thread_id'], ['mentor_threads.id'], name=op.f('fk_mentor_interventions_thread_id_mentor_threads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mentor_interventions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_interventions'))
    )
    op.create_index(op.f('ix_mentor_interventions_organization_id'), 'mentor_interventions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mentor_interventions_user_id'), 'mentor_interventions', ['user_id'], unique=False)
    op.create_table('mentor_messages',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider_generated', sa.Boolean(), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mentor_messages_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['thread_id'], ['mentor_threads.id'], name=op.f('fk_mentor_messages_thread_id_mentor_threads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mentor_messages_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_messages'))
    )
    op.create_index('ix_mentor_message_thread_time', 'mentor_messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('mission_objectives',
    sa.Column('mission_stage_id', sa.Uuid(), nullable=False),
    sa.Column('stable_key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('skill_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_stage_id'], ['mission_stages.id'], name=op.f('fk_mission_objectives_mission_stage_id_mission_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_objectives'))
    )
    op.create_table('mission_sessions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_version_id', sa.Uuid(), nullable=False),
    sa.Column('current_stage_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_stage_id'], ['mission_stages.id'], name=op.f('fk_mission_sessions_current_stage_id_mission_stages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mission_version_id'], ['mission_versions.id'], name=op.f('fk_mission_sessions_mission_version_id_mission_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mission_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mission_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_sessions'))
    )
    op.create_index('ix_mission_session_owner', 'mission_sessions', ['organization_id', 'user_id', 'created_at'], unique=False)
    op.create_table('portfolio_artifacts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('verification_state', sa.String(length=30), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_portfolio_artifacts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_artifacts_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolio_artifacts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_artifacts'))
    )
    op.create_index(op.f('ix_portfolio_artifacts_organization_id'), 'portfolio_artifacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_portfolio_artifacts_user_id'), 'portfolio_artifacts', ['user_id'], unique=False)
    op.create_table('project_reviews',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('criterion_results', sa.JSON(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_project_reviews_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_project_reviews_reviewer_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], name=op.f('fk_project_reviews_rubric_id_rubrics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submissions.id'], name=op.f('fk_project_reviews_submission_id_project_submissions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_reviews'))
    )
    op.create_index(op.f('ix_project_reviews_organization_id'), 'project_reviews', ['organization_id'], unique=False)
    op.create_table('question_responses',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_version_id', sa.Uuid(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('evaluator_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_question_responses_attempt_id_assessment_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_question_responses_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], name=op.f('fk_question_responses_question_version_id_question_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_question_responses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_responses')),
    sa.UniqueConstraint('attempt_id', 'question_version_id', name=op.f('uq_question_responses_attempt_id'))
    )
    op.create_index(op.f('ix_question_responses_organization_id'), 'question_responses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_question_responses_user_id'), 'question_responses', ['user_id'], unique=False)
    op.create_table('recommendation_decisions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_recommendation_decisions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_decisions_recommendation_id_recommendations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_decisions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_decisions'))
    )
    op.create_index(op.f('ix_recommendation_decisions_organization_id'), 'recommendation_decisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recommendation_decisions_user_id'), 'recommendation_decisions', ['user_id'], unique=False)
    op.create_table('retrieval_queries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('index_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_retrieval_queries_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['thread_id'], ['mentor_threads.id'], name=op.f('fk_retrieval_queries_thread_id_mentor_threads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_retrieval_queries_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_queries'))
    )
    op.create_index(op.f('ix_retrieval_queries_organization_id'), 'retrieval_queries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retrieval_queries_user_id'), 'retrieval_queries', ['user_id'], unique=False)
    op.create_table('investigation_replays',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_session_id', sa.Uuid(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('turning_points', sa.JSON(), nullable=False),
    sa.Column('missed_evidence', sa.JSON(), nullable=False),
    sa.Column('alternate_approaches', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generator_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_session_id'], ['mission_sessions.id'], name=op.f('fk_investigation_replays_mission_session_id_mission_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_investigation_replays_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_investigation_replays_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_replays')),
    sa.UniqueConstraint('mission_session_id', name=op.f('uq_investigation_replays_mission_session_id'))
    )
    op.create_index(op.f('ix_investigation_replays_organization_id'), 'investigation_replays', ['organization_id'], unique=False)
    op.create_index(op.f('ix_investigation_replays_user_id'), 'investigation_replays', ['user_id'], unique=False)
    op.create_table('mission_actions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_session_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=160), nullable=True),
    sa.Column('learner_input', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_session_id'], ['mission_sessions.id'], name=op.f('fk_mission_actions_mission_session_id_mission_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mission_actions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['mission_stages.id'], name=op.f('fk_mission_actions_stage_id_mission_stages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mission_actions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_actions'))
    )
    op.create_index('ix_mission_action_timeline', 'mission_actions', ['mission_session_id', 'sequence'], unique=False)
    op.create_table('mission_evidence',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_session_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_key', sa.String(length=120), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_session_id'], ['mission_sessions.id'], name=op.f('fk_mission_evidence_mission_session_id_mission_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mission_evidence_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mission_evidence_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_evidence')),
    sa.UniqueConstraint('mission_session_id', 'evidence_key', name=op.f('uq_mission_evidence_mission_session_id'))
    )
    op.create_index(op.f('ix_mission_evidence_organization_id'), 'mission_evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mission_evidence_user_id'), 'mission_evidence', ['user_id'], unique=False)
    op.create_table('mission_hint_uses',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_session_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hint_type', sa.String(length=50), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_session_id'], ['mission_sessions.id'], name=op.f('fk_mission_hint_uses_mission_session_id_mission_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mission_hint_uses_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['mission_stages.id'], name=op.f('fk_mission_hint_uses_stage_id_mission_stages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mission_hint_uses_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_hint_uses'))
    )
    op.create_index(op.f('ix_mission_hint_uses_organization_id'), 'mission_hint_uses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mission_hint_uses_user_id'), 'mission_hint_uses', ['user_id'], unique=False)
    op.create_table('mission_results',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_session_id', sa.Uuid(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('conceptual_score', sa.Float(), nullable=False),
    sa.Column('practical_score', sa.Float(), nullable=False),
    sa.Column('decision_score', sa.Float(), nullable=False),
    sa.Column('independence_score', sa.Float(), nullable=False),
    sa.Column('reporting_score', sa.Float(), nullable=False),
    sa.Column('evaluator_version', sa.String(length=40), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_session_id'], ['mission_sessions.id'], name=op.f('fk_mission_results_mission_session_id_mission_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mission_results_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mission_results_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_results')),
    sa.UniqueConstraint('mission_session_id', name=op.f('uq_mission_results_mission_session_id'))
    )
    op.create_index(op.f('ix_mission_results_organization_id'), 'mission_results', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mission_results_user_id'), 'mission_results', ['user_id'], unique=False)
    op.create_table('mission_submissions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_session_id', sa.Uuid(), nullable=False),
    sa.Column('report_body', sa.Text(), nullable=False),
    sa.Column('learner_authored', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_session_id'], ['mission_sessions.id'], name=op.f('fk_mission_submissions_mission_session_id_mission_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mission_submissions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mission_submissions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_submissions'))
    )
    op.create_index(op.f('ix_mission_submissions_organization_id'), 'mission_submissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mission_submissions_user_id'), 'mission_submissions', ['user_id'], unique=False)
    op.create_table('retrieval_results',
    sa.Column('retrieval_query_id', sa.Uuid(), nullable=False),
    sa.Column('publication_id', sa.String(length=160), nullable=False),
    sa.Column('publication_version', sa.String(length=40), nullable=False),
    sa.Column('chunk_id', sa.String(length=160), nullable=False),
    sa.Column('lexical_score', sa.Float(), nullable=False),
    sa.Column('vector_score', sa.Float(), nullable=True),
    sa.Column('hybrid_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['retrieval_query_id'], ['retrieval_queries.id'], name=op.f('fk_retrieval_results_retrieval_query_id_retrieval_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_results'))
    )
    op.create_index(op.f('ix_retrieval_results_retrieval_query_id'), 'retrieval_results', ['retrieval_query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_results_retrieval_query_id'), table_name='retrieval_results')
    op.drop_table('retrieval_results')
    op.drop_index(op.f('ix_mission_submissions_user_id'), table_name='mission_submissions')
    op.drop_index(op.f('ix_mission_submissions_organization_id'), table_name='mission_submissions')
    op.drop_table('mission_submissions')
    op.drop_index(op.f('ix_mission_results_user_id'), table_name='mission_results')
    op.drop_index(op.f('ix_mission_results_organization_id'), table_name='mission_results')
    op.drop_table('mission_results')
    op.drop_index(op.f('ix_mission_hint_uses_user_id'), table_name='mission_hint_uses')
    op.drop_index(op.f('ix_mission_hint_uses_organization_id'), table_name='mission_hint_uses')
    op.drop_table('mission_hint_uses')
    op.drop_index(op.f('ix_mission_evidence_user_id'), table_name='mission_evidence')
    op.drop_index(op.f('ix_mission_evidence_organization_id'), table_name='mission_evidence')
    op.drop_table('mission_evidence')
    op.drop_index('ix_mission_action_timeline', table_name='mission_actions')
    op.drop_table('mission_actions')
    op.drop_index(op.f('ix_investigation_replays_user_id'), table_name='investigation_replays')
    op.drop_index(op.f('ix_investigation_replays_organization_id'), table_name='investigation_replays')
    op.drop_table('investigation_replays')
    op.drop_index(op.f('ix_retrieval_queries_user_id'), table_name='retrieval_queries')
    op.drop_index(op.f('ix_retrieval_queries_organization_id'), table_name='retrieval_queries')
    op.drop_table('retrieval_queries')
    op.drop_index(op.f('ix_recommendation_decisions_user_id'), table_name='recommendation_decisions')
    op.drop_index(op.f('ix_recommendation_decisions_organization_id'), table_name='recommendation_decisions')
    op.drop_table('recommendation_decisions')
    op.drop_index(op.f('ix_question_responses_user_id'), table_name='question_responses')
    op.drop_index(op.f('ix_question_responses_organization_id'), table_name='question_responses')
    op.drop_table('question_responses')
    op.drop_index(op.f('ix_project_reviews_organization_id'), table_name='project_reviews')
    op.drop_table('project_reviews')
    op.drop_index(op.f('ix_portfolio_artifacts_user_id'), table_name='portfolio_artifacts')
    op.drop_index(op.f('ix_portfolio_artifacts_organization_id'), table_name='portfolio_artifacts')
    op.drop_table('portfolio_artifacts')
    op.drop_index('ix_mission_session_owner', table_name='mission_sessions')
    op.drop_table('mission_sessions')
    op.drop_table('mission_objectives')
    op.drop_index('ix_mentor_message_thread_time', table_name='mentor_messages')
    op.drop_table('mentor_messages')
    op.drop_index(op.f('ix_mentor_interventions_user_id'), table_name='mentor_interventions')
    op.drop_index(op.f('ix_mentor_interventions_organization_id'), table_name='mentor_interventions')
    op.drop_table('mentor_interventions')
    op.drop_table('membership_roles')
    op.drop_index('ix_diagnostic_owner_started', table_name='diagnostic_attempts')
    op.drop_table('diagnostic_attempts')
    op.drop_index('ix_skill_evidence_owner_time', table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_index('ix_sessions_user_expires', table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_safety_events_user_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_organization_id'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_table('rubric_criteria')
    op.drop_index('ix_recommendation_owner_status', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('question_versions')
    op.drop_index('ix_project_submission_owner', table_name='project_submissions')
    op.drop_table('project_submissions')
    op.drop_table('portfolios')
    op.drop_index('ix_membership_user_active', table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_table('mission_stages')
    op.drop_index(op.f('ix_mentor_threads_user_id'), table_name='mentor_threads')
    op.drop_index(op.f('ix_mentor_threads_organization_id'), table_name='mentor_threads')
    op.drop_table('mentor_threads')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_organization_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index('ix_learning_session_owner_start', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_learner_skill_states_user_id'), table_name='learner_skill_states')
    op.drop_index(op.f('ix_learner_skill_states_organization_id'), table_name='learner_skill_states')
    op.drop_table('learner_skill_states')
    op.drop_index(op.f('ix_learner_profiles_organization_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_learner_preferences_user_id'), table_name='learner_preferences')
    op.drop_index(op.f('ix_learner_preferences_organization_id'), table_name='learner_preferences')
    op.drop_table('learner_preferences')
    op.drop_index('ix_notes_owner_lesson', table_name='learner_notes')
    op.drop_table('learner_notes')
    op.drop_table('learner_misconceptions')
    op.drop_index(op.f('ix_learner_goals_user_id'), table_name='learner_goals')
    op.drop_index(op.f('ix_learner_goals_organization_id'), table_name='learner_goals')
    op.drop_table('learner_goals')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_organization_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_completion_records_verification_id'), table_name='completion_records')
    op.drop_index(op.f('ix_completion_records_user_id'), table_name='completion_records')
    op.drop_index(op.f('ix_completion_records_organization_id'), table_name='completion_records')
    op.drop_table('completion_records')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_organization_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index('ix_audit_tenant_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_assessment_attempt_owner', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index(op.f('ix_ai_usage_events_user_id'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_organization_id'), table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    op.drop_table('user_profiles')
    op.drop_table('skill_dependencies')
    op.drop_table('rubrics')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_questions_skill_key'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('project_milestones')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('mission_versions')
    op.drop_table('misconceptions')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_table('assessment_versions')
    op.drop_table('ai_evaluation_results')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_stable_key'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_table('projects')
    op.drop_table('permissions')
    op.drop_table('missions')
    op.drop_table('assessments')
    op.drop_table('ai_evaluation_cases')
    # ### end Alembic commands ###
