import { useQuery, useQueryClient } from "@tanstack/react-query";
import { FormEvent, useState } from "react";
import { Link, Route, Switch } from "wouter";
import { apiFetch } from "../../lib/api-client";

type Profile = { headline?: string; biography?: string; career_goals?: string; experience_level?: string; portfolio_visibility: string; public_slug?: string; domains: string[]; technical_interests: string[]; languages: string[]; links: Record<string, string> };
type PassportSkill = { skill_id: string; skill_name: string; mastery_level: number; confidence: number; evidence_count: number; verification_status: string; last_demonstrated: string | null };

function Nav() {
  return <nav className="portal-subnav" aria-label="Career workspace"><Link to="/career">Portfolio</Link><Link to="/career/passport">Skill Passport</Link><Link to="/career/readiness">Career readiness</Link><Link to="/career/transcript">Transcript</Link><Link to="/career/resume">Resume</Link><Link to="/career/profile">Profile settings</Link></nav>;
}

function ProfilePage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["career-profile"], queryFn: () => apiFetch<Profile>("/api/v1/career/profile") }); const [message, setMessage] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); await apiFetch("/api/v1/career/profile", { method: "PUT", body: JSON.stringify({ headline: d.get("headline") || null, biography: d.get("biography") || null, career_goals: d.get("career_goals") || null, experience_level: d.get("experience_level") || null, portfolio_visibility: d.get("portfolio_visibility"), domains: String(d.get("domains") || "").split(",").map(x => x.trim()).filter(Boolean), technical_interests: String(d.get("interests") || "").split(",").map(x => x.trim()).filter(Boolean), languages: String(d.get("languages") || "").split(",").map(x => x.trim()).filter(Boolean), links: {} }) }); setMessage("Professional profile saved."); await client.invalidateQueries({ queryKey: ["career-profile"] }); }
  if (query.isLoading) return <p role="status">Loading professional profile…</p>;
  const profile = query.data!;
  return <section className="portal-page"><Nav /><h1>Professional profile</h1><p>Career details are private unless you choose a visibility setting. Skills and achievements remain evidence-derived.</p><form className="portal-form" onSubmit={(e) => void save(e)}><label>Professional headline<input name="headline" defaultValue={profile.headline || ""} /></label><label>Biography<textarea name="biography" defaultValue={profile.biography || ""} /></label><label>Career goals<textarea name="career_goals" defaultValue={profile.career_goals || ""} /></label><label>Experience level<input name="experience_level" defaultValue={profile.experience_level || ""} /></label><label>Preferred cybersecurity domains<input name="domains" defaultValue={profile.domains.join(", ")} /></label><label>Technical interests<input name="interests" defaultValue={profile.technical_interests.join(", ")} /></label><label>Languages<input name="languages" defaultValue={profile.languages.join(", ")} /></label><label>Portfolio visibility<select name="portfolio_visibility" defaultValue={profile.portfolio_visibility}><option value="private">Private</option><option value="link_only">Link-only</option><option value="organization_only">Organization-only</option><option value="recruiter_only">Recruiter-only</option><option value="public">Public</option></select></label><button className="primary">Save profile</button>{message && <p role="status">{message}</p>}</form>{profile.public_slug && profile.portfolio_visibility === "public" && <p>Public portfolio link: <a href={`/api/v1/career-public/portfolios/${profile.public_slug}`}>View verified portfolio</a></p>}</section>;
}

function PassportPage() { const query = useQuery({ queryKey: ["career-passport"], queryFn: () => apiFetch<{ skills: PassportSkill[]; notice: string }>("/api/v1/career/passport") }); return <section className="portal-page"><Nav /><h1>CyberMentor Skill Passport</h1><p>Skills cannot be edited here. They are calculated from verified activity.</p>{query.isLoading && <p role="status">Loading verified skills…</p>}<div className="portal-list">{query.data?.skills.map(skill => <article key={skill.skill_id}><strong>{skill.skill_name}</strong><span>{skill.verification_status} · mastery {Math.round(skill.mastery_level * 100)}% · confidence {Math.round(skill.confidence * 100)}% · {skill.evidence_count} evidence records</span></article>)}</div>{query.data?.skills.length === 0 && <p>No verified skill evidence yet. Complete a trusted lab, mission, assessment, or reviewed project.</p>}</section>; }

function PortfolioPage() { const query = useQuery({ queryKey: ["career-portfolio"], queryFn: () => apiFetch<{ profile: Profile; evidence: { artifacts: { id: string; title: string; type: string }[]; completion_records: { id: string; scope_type: string; scope_id: string }[] }; timeline: { type: string; title: string; occurred_at: string }[] }>("/api/v1/career/portfolio") }); const client = useQueryClient(); const [message, setMessage] = useState(""); async function certificate(id: string) { const x = await apiFetch<{ certificate_id: string }>(`/api/v1/career/certificates/from-completion/${id}`, { method: "POST" }); setMessage(`Certificate ${x.certificate_id} issued from this verified completion.`); await client.invalidateQueries({ queryKey: ["career-portfolio"] }); }
return <section className="portal-page"><Nav /><h1>Professional portfolio</h1><p>{query.data?.profile.headline || "Build a verified professional story from your CyberMentor activity."}</p>{message && <p role="status">{message}</p>}<h2>Verified evidence</h2><div className="portal-list">{query.data?.evidence.artifacts.map(x => <article key={x.id}><strong>{x.title}</strong><span>{x.type}</span></article>)}{query.data?.evidence.completion_records.map(x => <article key={x.id}><strong>{x.scope_type}: {x.scope_id}</strong><button onClick={() => void certificate(x.id)}>Issue certificate</button></article>)}</div><h2>Professional timeline</h2><div className="portal-list">{query.data?.timeline.map((x, i) => <article key={`${x.type}-${i}`}><strong>{x.title}</strong><span>{new Date(x.occurred_at).toLocaleString()}</span></article>)}</div></section>; }

function ReadinessPage() { const query = useQuery({ queryKey: ["career-readiness"], queryFn: () => apiFetch<{ strengths: string[]; weaknesses: string[]; role_matches: { name: string; readiness_score: number; missing_skills: string[]; why: string }[] }>("/api/v1/career/readiness") }); return <section className="portal-page"><Nav /><h1>Career readiness</h1><p>This is a transparent evidence analysis, not a hiring prediction.</p><h2>Strengths</h2><p>{query.data?.strengths.join(", ") || "Insufficient verified evidence."}</p><h2>Role mapping</h2><div className="portal-list">{query.data?.role_matches.map(role => <article key={role.name}><strong>{role.name} — {role.readiness_score}% evidence coverage</strong><p>Missing: {role.missing_skills.join(", ") || "No required skill gaps detected"}</p><small>{role.why}</small></article>)}</div></section>; }

function TranscriptPage() { const query = useQuery({ queryKey: ["career-transcript"], queryFn: () => apiFetch<{ courses: { course: string; status: string }[]; certificates: { certificate_id: string; course: string; status: string }[]; limitations: string }>("/api/v1/career/transcript") }); return <section className="portal-page"><Nav /><h1>Digital transcript</h1><p><a href="/api/v1/career/transcript.pdf">Download verified transcript PDF</a></p><div className="portal-list">{query.data?.courses.map(x => <article key={x.course}><strong>{x.course}</strong><span>{x.status}</span></article>)}{query.data?.certificates.map(x => <article key={x.certificate_id}><strong>{x.course}</strong><span>Certificate {x.certificate_id} · {x.status}</span></article>)}</div><p>{query.data?.limitations}</p></section>; }

function ResumePage() { const query = useQuery({ queryKey: ["career-resume"], queryFn: () => apiFetch<{ headline: string | null; professional_summary: string | null; verified_skills: { name: string; evidence_count: number }[]; verified_projects: { title: string }[]; notice: string }>("/api/v1/career/resume") }); return <section className="portal-page"><Nav /><h1>Evidence-based resume</h1><p>{query.data?.notice}</p><h2>{query.data?.headline}</h2><p>{query.data?.professional_summary}</p><h2>Verified skills</h2><p>{query.data?.verified_skills.map(x => `${x.name} (${x.evidence_count} evidence)`).join(", ") || "No verified skills yet."}</p><h2>Reviewed projects</h2><p>{query.data?.verified_projects.map(x => x.title).join(", ") || "No human-reviewed projects yet."}</p></section>; }

export function CareerApp() { return <main className="portal-shell"><Switch><Route path="/career/profile" component={ProfilePage} /><Route path="/career/passport" component={PassportPage} /><Route path="/career/readiness" component={ReadinessPage} /><Route path="/career/transcript" component={TranscriptPage} /><Route path="/career/resume" component={ResumePage} /><Route path="/career" component={PortfolioPage} /></Switch></main>; }
